export const Hub = {
    Plaza: [
        ////"|--------------|--------------|--------------|--------------|",
        "", "", "",
        "Welcome, dearest visitor.",
        "",
        "           I have prepared this exhibit for you",
        "           to explore at your leisure.",
        "",
        "           It is my hope that it may serve",
        "           as a gentle introduction to",
        "           the nature of hyperbolic space,",
        "           and provide a point of reference",
        "           for the realm I hold within my heart -- the ORVEYL",
        "",
        "                             Thank you, and enjoy your stay!",
        "                                                     -- adc",
    ],

    Euclid: [
        ////"|--------------|--------------|--------------|--------------|",
        "[EUCLIDEAN GEOMETRY]",
        "",
        "       Named after the ancient Greek mathematician EUCLID,",
        "       who detailed its foundations in his treatise,",
        "       the Elements, circa 300 BC.",
        "",
        "       Euclidean geometry is the familiar geometry of",
        "       so-called flat space, where non-intersecting lines",
        "       remain equidistant, a triangle's angle sum is 180 degrees,",
        "       and similar figures can exist at any scale.",
        "",
        "       You are not in this kind of space right now!",
    ],

    EuclidAxioms: [
        ////"|--------------|--------------|--------------|--------------|",
        "[EUCLID'S AXIOMS]",
        "",
        "       Euclid postulated the following statements as",
        "       the logical basis for his reasoning in the Elements.",
        "",
        " I   - A line can be drawn between any two points.",
        "",
        " II  - Any segment of a line can be extended indefinitely.",
        "",
        " III - A circle of any radius can be drawn around any center.",
        "",
        " IV  - All right angles are congruent.",
        "",
        " V   - If two lines in the plane are met by another line,",
        "       and if the sum of the internal angles on one side",
        "       is less than two right angles, then the lines will",
        "       meet if sufficiently extended on that side."
    ],

    Euclids5th: [
        ////"|--------------|--------------|--------------|--------------|",
        "[EUCLID'S 5th POSTULATE]",
        "",
        "       Euclid's 5th postulate troubled geometers for centuries.",
        "       In contrast with the brevity of the other four,",
        "       it seemed to be a more complicated statement,",
        "       and not something so easily accepted as self-evident.",
        "",
        "       Its status as an axiom was questioned, and great efforts",
        "       were taken to derive it from the others.",
    ],

    NonEuclid: [
        ////"|--------------|--------------|--------------|--------------|",
        "[NON-EUCLIDEAN GEOMETRY]",
        "",
        "       The desire to tackle Euclid's 5th postulate",
        "       served as a driving force toward seemingly",
        "       impossible formulations of non-Euclidean geometry.",
        "",
        "       Despite their violation of Euclidean principles",
        "       that were believed to govern the universe,",
        "       these results, while perhaps unintuitive,",
        "       did not actually contain any logical errors or contradictions,",
        "       proving to describe a self-consistent geometry under scrutiny.",
        "",
        "       Non-Euclidean geometry began to develop on its own terms",
        "       in the 1800s, with the works of Lobachevsky and Bolyai",
        "       independently affirming its consistency.",
    ],

    Erlangen: [
        ////"|--------------|--------------|--------------|--------------|",
        "[KLEIN'S ERLANGEN PROGRAM]",
        "",
        "       In the 1870s, Felix Klein established a unified framework",
        "       to characterize both Euclidean and non-Euclidean geometries",
        "       within the more general structure of projective geometry.",
        "",
        "       Klein's work was groundbreaking in its examination of",
        "       geometric transformations and abstract symmetry groups,",
        "       and guided future developments in mathematics and physics.",
    ],

    CayleyKlein: [
        ////"|--------------|--------------|--------------|--------------|",
        "[CAYLEY-KLEIN METRICS]",
        "",
        "       In the setting of projective geometry, the notions of",
        "       distance, angle, and even betweenness are abandoned.",
        "",
        "       Instead, the focus is on the properties of",
        "       points and lines that remain invariant under",
        "       perspective transformations, most notably their incidences.",
        "",
        "       A Cayley-Klein metric is a tool for reintroducing",
        "       distance and angle measurement in the projective setting,",
        "       using a projective invariant called the cross-ratio.",
        "       Measurements are carried out with respect to an ABSOLUTE,",
        "       a given quadric (a conic, i.e. a circle, ellipse, etc.)",
        "       which represents the points at infinity -- the horizon",
        "       of the geometry it induces."
    ],

    Hyperbolic: [
        ////"|--------------|--------------|--------------|--------------|",
        "[HYPERBOLIC GEOMETRY]",
        "",
        "       Hyperbolic geometry is one such non-Euclidean case.",
        "       It is the geometry of negatively-curved space,",
        "       where non-intersecting lines diverge from one another,",
        "       a triangle's angle sum is less than 180 degrees,",
        "       and distance can be measured according to an absolute scale.",
        "",
        "       As a Cayley-Klein geometry, hyperbolic geometry has a",
        "       particularly beautiful and symmetric construction,",
        "       with its ABSOLUTE being a nondegenerate real quadric.",
        "",
        "       Analogous to the crochet models on display at MorYork,",
        "       which are regions of two-dimensional hyperbolic planes,",
        "       this virtual exhibit is an implementation of a",
        "       small region of three-dimensional hyperbolic space!",
    ],
};